# Generated by Django 5.0.2 on 2024-03-05 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inHive', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hive',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('hiveTitle', models.CharField(max_length=100)),
                ('hiveDescription', models.TextField()),
                ('intendedUsers', models.IntegerField()),
                ('hiveStartDate', models.DateField()),
                ('hiveEnDate', models.DateField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Completed', 'Completed'), ('Archived', 'Archived')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='QueenBee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('Member', 'Member'), ('QueenBee', 'QueenBee')], max_length=20)),
                ('hive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inHive.hive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inHive.user')),
            ],
        ),
        migrations.AddField(
            model_name='hive',
            name='queenBee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inHive.queenbee'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taskTitle', models.CharField(max_length=100)),
                ('taskDescription', models.TextField()),
                ('taskStartDate', models.DateField()),
                ('hiveEnDate', models.DateField()),
                ('assignedTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inHive.user')),
            ],
        ),
    ]
