# Generated by Django 5.0.2 on 2024-03-05 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inHive', '0003_rename_hiveendate_task_taskendate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hive',
            old_name='hiveEnDate',
            new_name='hiveEndDate',
        ),
    ]
