# Generated by Django 5.0.2 on 2024-03-06 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inHive', '0004_rename_hiveendate_hive_hiveenddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taskEnDate',
            new_name='taskEndDate',
        ),
    ]
