# Generated by Django 5.0.2 on 2024-03-07 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inHive', '0005_rename_taskendate_task_taskenddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hive',
            name='queenBee',
        ),
        migrations.RenameField(
            model_name='membership',
            old_name='user',
            new_name='User',
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('Member', 'Member'), ('QueenBee', 'QueenBee'), ('Soldier', 'Soldier')], max_length=20),
        ),
        migrations.DeleteModel(
            name='QueenBee',
        ),
    ]
