# Generated by Django 5.0.2 on 2024-03-08 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inHive', '0007_hive_hiveowner_task_hive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
    ]
